/**
 * @link
 * https://www.guilded.gg/docs/api/chat
 */

/**
 * https://www.guilded.gg/docs/api/chat/ChatMessage
 */
 export interface APIMessage {
    /** The ID of the message */
    id: string;
    /**
     * The type of chat message. 
     * "system" messages are generated by Guilded, 
     * while "default" messages are user or bot-generated.
     */
    type: APIMessageTypes;
    /** The ID of the server */
    serverId?: string;
    /** The ID of the channel */
    channelId: string;
    /** The content of this message */
    content?: string;
    /** The embeds of this message (min items: 1; max items 10) */
    embeds?: APIEmbed[];
    /** Message IDs that were replied to (min items 1; max items 5) */
    replyMessageIds?: string[];
    /** If set, this message will only be seen by those mentioned or replied to */
    isPrivate?: boolean;
    /** If set, this message did not notify mention or reply recipients (default false) */
    isSilent?: boolean;
    /** The ISO 8601 timestamp that the message was created at */
    createdAt: string;
    /**
     * The ID of the user who created this message 
     * (Note: If this event has createdByWebhookId present, 
     * this field will still be populated, but can be ignored. 
     * In this case, the value of this field will always be Ann6LewA)
     */
    createdByWebhookId?: string;
    /** The ISO 8601 timestamp that the message was updated at, if relevant */
    updatedAt?: string;
};

export type APIChatMessage = APIMessage;
export type APIMessageTypes = "default" | "system";

/**
 * https://www.guilded.gg/docs/api/chat/ChatEmbed
 */
export interface APIEmbed {
    /** Main header of the embed (max length 256) */
    title?: string;
    /** Subtext of the embed (max length 2048) */
    description?: string;
    /** URL to linkify the title field with (max length 1024; regex ^(?!attachment)) */
    url?: string;
    /** Decimal value of the color that the left border should be (min 0; max 16777215) */
    color?: number;
    /** A small section at the bottom of the embed */
    footer?: APIEmbedFooter;
    /** A timestamp to put in the footer */
    timestamp?: string;
    /** An image to the right of the embed's content */
    thumbnail?: APIEmbedThumbnail;
    /** The main picture to associate with the embed */
    image?: APIEmbedImage;
    /** A small section above the title of the embed */
    author?: APIEmbedAuthor;
    /** Table-like cells to add to the embed (max items 25) */
    fields?: APIEmbedField[];
};

export interface APIEmbedFooter {
    /** URL of a small image to put in the footer */
    icon_url?: string;
    /** Text of the footer */
    text: string;
};

export interface APIEmbedThumbnail {
    /** URL of the image */
    url?: string;
};

export interface APIEmbedImage {
    /** URL of the image */
    url?: string;
};

export interface APIEmbedAuthor {
    /** Name of the author */
    name?: string;
    /** URL to linkify the author's name field */
    url?: string;
    /** URL of a small image to display to the left of the author's name */
    icon_url?: string;
};

export interface APIEmbedField {
    /** Header of the table-like cell (max length 256) */
    name: string;
    /** Subtext of the table-like cell (max length 1024) */
    value: string;
    /** If the field should wrap or not (default false) */
    inline?: boolean;
};

export type ChatMessage = APIMessage;
export type ChatEmbed = APIEmbed;

/**
 * https://www.guilded.gg/docs/api/chat/ChannelMessageCreate
 */
export type APIPostMessageResponse = APIChatMessage;
export interface APIPostMessageBody {
        /** If set, this message will only be seen by those mentioned or replied to */
        isPrivate?: boolean;
        /** If set, this message will not notify any mentioned users or roles (default false) */
        isSilent?: boolean;
        /** Message IDs to reply to (min items 1; max items 5) */
        replyMessageIds?: string[];
        /** The content of the message (min length 1; max length 4000) */
        content?: string;
        /**
         * At this time, only one embed is supported per message, and attachments are not supported.
         * If you need to send more than one embed or upload attachments, consider creating the message via a webhook. 
         * (min items 1; max items 1)
         */
        embeds?: APIEmbed[];
};

/**
 * https://www.guilded.gg/docs/api/chat/ChannelMessageReadMany
 */
export interface APIGetMessagesQuery {
        /** An ISO 8601 timestamp that will be used to filter out results for the current page */
        before?: string;
        /**
         * An ISO 8601 timestamp that will be used to filter out results for the current page. 
         * Order may be reversed when compared to before or omitting this parameter altogether
         */
        after?: string;
        /** The max size of the page (default 50; min 1; max 100) */
        limit?: number;
        /** Whether to include private messages between all users in response (default false) */
        includePrivate?: boolean;
};

/**
 * https://www.guilded.gg/docs/api/chat/ChannelMessageRead
 */
export type APIGetMessageResponse = APIMessage;

/**
 * https://www.guilded.gg/docs/api/chat/ChannelMessageUpdate
 */
export interface APIPatchMessageBody {
    /** The content of the message */
    content?: string;
    /** The embeds of the message (min items 1; max items 2) */
    embeds?: APIEmbed[];
};